#!/usr/bin/env python
# Info module template

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by
#   https://github.com/jgroom33/vmware_rest_code_generator
#
# Do not edit this file manually.
#
# Changes should be made in the swagger used to
#   generate this file or in the generator
#
#############################################

from __future__ import absolute_import, division, print_function

__metaclass__ = type
import socket
import json

DOCUMENTATION = """
module: commissioning_api_v1_scripts
short_description: Handle resource of type commissioning_api_v1_scripts
description: Handle resource of type commissioning_api_v1_scripts
options:
  devicetype:
    description:
    - Device type planned network i.e., 6500, Waveserver
    - Used by I(state=['get'])
    type: str
  format:
    description:
    - Script format to be returned i.e., ztpScript, json, cli
    - Used by I(state=['get'])
    type: str
  nodename:
    description:
    - Node name in a planned network
    - Used by I(state=['get'])
    type: str
  policyid:
    description:
    - Policy id of commissioning policy to be used
    - Used by I(state=['post'])
    type: str
  projectname:
    description:
    - Project Name of planned network
    - Required with I(state=['delete', 'get', 'post'])
    - Used by I(state=['delete', 'get', 'post'])
    type: str
  shelfId:
    description:
    - Shelf Id of the generated script e.g. Shelf number 0,1,2,11,21 etc or ALL
    - Used by I(state=['get'])
    type: str
  state:
    choices:
    - delete
    - get
    - post
    description: []
    type: str
author: []
version_added: 1.0.0
requirements:
- python >= 3.6
"""
IN_QUERY_PARAMETER = [
    "devicetype",
    "format",
    "nodename",
    "policyid",
    "projectname",
    "shelfId",
]
from ansible.module_utils.basic import env_fallback

try:
    from ansible_module.turbo.module import AnsibleTurboModule as AnsibleModule
except ImportError:
    from ansible.module_utils.basic import AnsibleModule
from ansible_collections.ciena.mcp.plugins.module_utils.mcp import (
    gen_args,
    open_session,
    update_changed_flag,
)


def prepare_argument_spec():
    argument_spec = {
        "mcp_hostname": dict(
            type="str", required=False, fallback=(env_fallback, ["MCP_HOST"])
        ),
        "mcp_username": dict(
            type="str", required=False, fallback=(env_fallback, ["MCP_USER"])
        ),
        "mcp_password": dict(
            type="str",
            required=False,
            no_log=True,
            fallback=(env_fallback, ["MCP_PASSWORD"]),
        ),
    }
    argument_spec["state"] = {"type": "str", "choices": ["delete", "get", "post"]}
    argument_spec["shelfId"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["projectname"] = {
        "type": "str",
        "operationIds": ["delete", "get", "post"],
    }
    argument_spec["policyid"] = {"type": "str", "operationIds": ["post"]}
    argument_spec["nodename"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["format"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["devicetype"] = {"type": "str", "operationIds": ["get"]}
    return argument_spec


async def main():
    module_args = prepare_argument_spec()
    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)
    session = await open_session(
        mcp_hostname=module.params["mcp_hostname"],
        mcp_username=module.params["mcp_username"],
        mcp_password=module.params["mcp_password"],
    )
    result = await entry_point(module, session)
    module.exit_json(**result)


def url(params):
    return "https://{mcp_hostname}/commissioning/api/v1/scripts/".format(**params)


async def entry_point(module, session):
    func = globals()[("_" + module.params["state"])]
    return await func(module.params, session)


async def _delete(params, session):
    _url = "https://{mcp_hostname}/commissioning/api/v1/scripts/".format(
        **params
    ) + gen_args(params, IN_QUERY_PARAMETER)
    async with session.delete(_url) as resp:
        content_types = [
            "application/json-patch+json",
            "application/vnd.api+json",
            "application/json",
        ]
        try:
            if resp.headers["Content-Type"] in content_types:
                _json = await resp.json()
            else:
                print("response Content-Type not supported")
        except KeyError:
            _json = {}
        return await update_changed_flag(_json, resp.status, "delete")


async def _get(params, session):
    _url = "https://{mcp_hostname}/commissioning/api/v1/scripts/".format(
        **params
    ) + gen_args(params, IN_QUERY_PARAMETER)
    async with session.get(_url) as resp:
        content_types = [
            "application/json-patch+json",
            "application/vnd.api+json",
            "application/json",
        ]
        try:
            if resp.headers["Content-Type"] in content_types:
                _json = await resp.json()
            else:
                print("response Content-Type not supported")
        except KeyError:
            _json = {}
        return await update_changed_flag(_json, resp.status, "get")


async def _post(params, session):
    accepted_fields = ["policyid", "projectname"]
    spec = {}
    for i in accepted_fields:
        if params[i] is not None:
            spec[i] = params[i]
    _url = "https://{mcp_hostname}/commissioning/api/v1/scripts/".format(
        **params
    ) + gen_args(params, IN_QUERY_PARAMETER)
    async with session.post(_url, json=spec) as resp:
        content_types = [
            "application/json-patch+json",
            "application/vnd.api+json",
            "application/json",
        ]
        try:
            if resp.headers["Content-Type"] in content_types:
                _json = await resp.json()
            else:
                print("response Content-Type not supported")
        except KeyError:
            _json = {}
        return await update_changed_flag(_json, resp.status, "post")


if __name__ == "__main__":
    import asyncio

    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
