#!/usr/bin/env python
# Info module template

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by
#   https://github.com/jgroom33/vmware_rest_code_generator
#
# Do not edit this file manually.
#
# Changes should be made in the swagger used to
#   generate this file or in the generator
#
#############################################

from __future__ import absolute_import, division, print_function

__metaclass__ = type
import socket
import json

DOCUMENTATION = """
module: configmgmt_api_v2_profiles
short_description: Handle resource of type configmgmt_api_v2_profiles
description: Handle resource of type configmgmt_api_v2_profiles
options:
  imageLocation:
    description:
    - Used by I(state=['post'])
    type: str
  ipAddress:
    description:
    - (Optional) Ip Address of Network Construct
    - Used by I(state=['get', 'post'])
    type: str
  limit:
    description:
    - The size of a returned page
    - Used by I(state=['get'])
    type: str
  metaDataFields:
    description:
    - '(Optional) List of meta data to be included. The allowed values are: profileType,
      protocolType, storageMethod'
    - Used by I(state=['get'])
    type: str
  name:
    description:
    - List of profile names
    - Used by I(state=['get', 'post'])
    type: str
  offset:
    description:
    - (Optional) Offset for current index of data to return
    - Used by I(state=['get'])
    type: str
  port:
    description:
    - The NE Maintenance profiles by port to be retrieved.
    - Used by I(state=['get', 'post'])
    type: int
  profileId:
    description:
    - List of profile Ids
    - Used by I(state=['get'])
    type: str
  profileType:
    description:
    - The NE Maintenance profiles by profile type to be retrieved.
    - Used by I(state=['get', 'post'])
    type: str
  protocolType:
    description:
    - The NE Maintenance profiles by protocol type to be retrieved.
    - Used by I(state=['get', 'post'])
    type: str
  releaseNumber:
    description:
    - The NE Maintenance upgrade profiles by release number to be retrieved.
    - Used by I(state=['get'])
    type: str
  searchFields:
    description:
    - (Optional) List of comma separated fields to search on. If none are specified,
      all supported fields are implied.
    - Used by I(state=['get'])
    type: str
  searchText:
    description:
    - (Optional) The searchable text
    - Used by I(state=['get'])
    type: str
  sortBy:
    description:
    - (Optional) List of comma separated fields by which to sort the result. A dash
      or negative sign before a field indicates descending order; by default ascending
      order is used
    - Used by I(state=['get'])
    type: str
  sshPort:
    description:
    - The NE Maintenance profiles by sshPort to be retrieved.
    - Used by I(state=['get'])
    type: int
  state:
    choices:
    - get
    - post
    description: []
    type: str
  storageMethod:
    description:
    - The NE Maintenance profiles by storage method to be retrieved.
    - Used by I(state=['get', 'post'])
    type: str
  typeGroup:
    description:
    - The NE Maintenance profiles by typeGroup to be retrieved.
    - Used by I(state=['get'])
    type: str
  userName:
    description:
    - Used by I(state=['post'])
    type: str
  userPassword:
    description:
    - Used by I(state=['post'])
    type: str
author: []
version_added: 1.0.0
requirements:
- python >= 3.6
"""
IN_QUERY_PARAMETER = [
    "limit",
    "metaDataFields",
    "offset",
    "profileId",
    "releaseNumber",
    "searchFields",
    "searchText",
    "sortBy",
    "sshPort",
    "typeGroup",
]
from ansible.module_utils.basic import env_fallback

try:
    from ansible_module.turbo.module import AnsibleTurboModule as AnsibleModule
except ImportError:
    from ansible.module_utils.basic import AnsibleModule
from ansible_collections.ciena.mcp.plugins.module_utils.mcp import (
    gen_args,
    open_session,
    update_changed_flag,
)


def prepare_argument_spec():
    argument_spec = {
        "mcp_hostname": dict(
            type="str", required=False, fallback=(env_fallback, ["MCP_HOST"])
        ),
        "mcp_username": dict(
            type="str", required=False, fallback=(env_fallback, ["MCP_USER"])
        ),
        "mcp_password": dict(
            type="str",
            required=False,
            no_log=True,
            fallback=(env_fallback, ["MCP_PASSWORD"]),
        ),
    }
    argument_spec["userPassword"] = {"type": "str", "operationIds": ["post"]}
    argument_spec["userName"] = {"type": "str", "operationIds": ["post"]}
    argument_spec["typeGroup"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["storageMethod"] = {"type": "str", "operationIds": ["get", "post"]}
    argument_spec["state"] = {"type": "str", "choices": ["get", "post"]}
    argument_spec["sshPort"] = {"type": "int", "operationIds": ["get"]}
    argument_spec["sortBy"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["searchText"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["searchFields"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["releaseNumber"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["protocolType"] = {"type": "str", "operationIds": ["get", "post"]}
    argument_spec["profileType"] = {"type": "str", "operationIds": ["get", "post"]}
    argument_spec["profileId"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["port"] = {"type": "int", "operationIds": ["get", "post"]}
    argument_spec["offset"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["name"] = {"type": "str", "operationIds": ["get", "post"]}
    argument_spec["metaDataFields"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["limit"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["ipAddress"] = {"type": "str", "operationIds": ["get", "post"]}
    argument_spec["imageLocation"] = {"type": "str", "operationIds": ["post"]}
    return argument_spec


async def main():
    module_args = prepare_argument_spec()
    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)
    session = await open_session(
        mcp_hostname=module.params["mcp_hostname"],
        mcp_username=module.params["mcp_username"],
        mcp_password=module.params["mcp_password"],
    )
    result = await entry_point(module, session)
    module.exit_json(**result)


def url(params):
    return "https://{mcp_hostname}/configmgmt/api/v2/profiles".format(**params)


async def entry_point(module, session):
    func = globals()[("_" + module.params["state"])]
    return await func(module.params, session)


async def _get(params, session):
    accepted_fields = [
        "ipAddress",
        "name",
        "port",
        "profileType",
        "protocolType",
        "storageMethod",
    ]
    spec = {}
    for i in accepted_fields:
        if params[i] is not None:
            spec[i] = params[i]
    _url = "https://{mcp_hostname}/configmgmt/api/v2/profiles".format(
        **params
    ) + gen_args(params, IN_QUERY_PARAMETER)
    async with session.get(_url, json=spec) as resp:
        content_types = [
            "application/json-patch+json",
            "application/vnd.api+json",
            "application/json",
        ]
        try:
            if resp.headers["Content-Type"] in content_types:
                _json = await resp.json()
            else:
                print("response Content-Type not supported")
        except KeyError:
            _json = {}
        return await update_changed_flag(_json, resp.status, "get")


async def _post(params, session):
    accepted_fields = [
        "imageLocation",
        "ipAddress",
        "name",
        "port",
        "profileType",
        "protocolType",
        "storageMethod",
        "userName",
        "userPassword",
    ]
    spec = {}
    for i in accepted_fields:
        if params[i] is not None:
            spec[i] = params[i]
    _url = "https://{mcp_hostname}/configmgmt/api/v2/profiles".format(
        **params
    ) + gen_args(params, IN_QUERY_PARAMETER)
    async with session.post(_url, json=spec) as resp:
        content_types = [
            "application/json-patch+json",
            "application/vnd.api+json",
            "application/json",
        ]
        try:
            if resp.headers["Content-Type"] in content_types:
                _json = await resp.json()
            else:
                print("response Content-Type not supported")
        except KeyError:
            _json = {}
        return await update_changed_flag(_json, resp.status, "post")


if __name__ == "__main__":
    import asyncio

    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
