#!/usr/bin/env python
# Info module template

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by
#   https://github.com/jgroom33/vmware_rest_code_generator
#
# Do not edit this file manually.
#
# Changes should be made in the swagger used to
#   generate this file or in the generator
#
#############################################

from __future__ import absolute_import, division, print_function

__metaclass__ = type
import socket
import json

DOCUMENTATION = """
module: domains_validate
short_description: Handle resource of type domains_validate
description: Handle resource of type domains_validate
options:
  accessUrl:
    description:
    - Access URL to the domain
    - Used by I(state=['post'])
    type: str
  address:
    description:
    - Address of the domain
    - 'Validate attributes are:'
    - ' - C(city) (str): City'
    - ' - C(country) (str): Country'
    - ' - C(latitude) (number): Latitude'
    - ' - C(longitude) (number): Longitude'
    - ' - C(state) (str): State/province'
    - ' - C(street) (str): Street'
    - ' - C(zip) (str): Postal/zip code'
    - Used by I(state=['post'])
    type: dict
  description:
    description:
    - Detailed description
    - Used by I(state=['post'])
    type: str
  full:
    description:
    - Whether to perform a full validation request
    - Required with I(state=['post'])
    - Used by I(state=['post'])
    type: bool
  onlyEnableTypes:
    description:
    - When non-empty, only enable these resource types in the domain
    - Used by I(state=['post'])
    type: list
  operationMode:
    description:
    - Operation mode of this domain
    - Used by I(state=['post'])
    type: str
  properties:
    description:
    - Properties the domain
    - 'Validate attributes are:'
    - ' - C(obj) (list): '
    - Used by I(state=['post'])
    type: dict
  rpId:
    description:
    - Resource provider managing this domain
    - Used by I(state=['post'])
    type: str
  state:
    choices:
    - post
    description: []
    type: str
  tenantId:
    description:
    - Orchestrator tenant ID for the domain owner (if unspecified defaults to requester)
    - Used by I(state=['post'])
    type: str
  title:
    description:
    - Descriptive name/title of domain
    - Used by I(state=['post'])
    type: str
author: []
version_added: 1.0.0
requirements:
- python >= 3.6
"""
IN_QUERY_PARAMETER = ["full"]
from ansible.module_utils.basic import env_fallback

try:
    from ansible_module.turbo.module import AnsibleTurboModule as AnsibleModule
except ImportError:
    from ansible.module_utils.basic import AnsibleModule
from ansible_collections.ciena.mcp.plugins.module_utils.mcp import (
    gen_args,
    open_session,
    update_changed_flag,
)


def prepare_argument_spec():
    argument_spec = {
        "mcp_hostname": dict(
            type="str", required=False, fallback=(env_fallback, ["MCP_HOST"])
        ),
        "mcp_username": dict(
            type="str", required=False, fallback=(env_fallback, ["MCP_USER"])
        ),
        "mcp_password": dict(
            type="str",
            required=False,
            no_log=True,
            fallback=(env_fallback, ["MCP_PASSWORD"]),
        ),
    }
    argument_spec["title"] = {"type": "str", "operationIds": ["post"]}
    argument_spec["tenantId"] = {"type": "str", "operationIds": ["post"]}
    argument_spec["state"] = {"type": "str", "choices": ["post"]}
    argument_spec["rpId"] = {"type": "str", "operationIds": ["post"]}
    argument_spec["properties"] = {"type": "dict", "operationIds": ["post"]}
    argument_spec["operationMode"] = {"type": "str", "operationIds": ["post"]}
    argument_spec["onlyEnableTypes"] = {"type": "list", "operationIds": ["post"]}
    argument_spec["full"] = {"type": "bool", "operationIds": ["post"]}
    argument_spec["description"] = {"type": "str", "operationIds": ["post"]}
    argument_spec["address"] = {"type": "dict", "operationIds": ["post"]}
    argument_spec["accessUrl"] = {"type": "str", "operationIds": ["post"]}
    return argument_spec


async def main():
    module_args = prepare_argument_spec()
    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)
    session = await open_session(
        mcp_hostname=module.params["mcp_hostname"],
        mcp_username=module.params["mcp_username"],
        mcp_password=module.params["mcp_password"],
    )
    result = await entry_point(module, session)
    module.exit_json(**result)


def url(params):
    return "https://{mcp_hostname}/bpocore/market/api/v1/domains/validate".format(
        **params
    )


async def entry_point(module, session):
    func = globals()[("_" + module.params["state"])]
    return await func(module.params, session)


async def _post(params, session):
    accepted_fields = [
        "accessUrl",
        "address",
        "description",
        "full",
        "onlyEnableTypes",
        "operationMode",
        "properties",
        "rpId",
        "tenantId",
        "title",
    ]
    spec = {}
    for i in accepted_fields:
        if params[i] is not None:
            spec[i] = params[i]
    _url = "https://{mcp_hostname}/bpocore/market/api/v1/domains/validate".format(
        **params
    ) + gen_args(params, IN_QUERY_PARAMETER)
    async with session.post(_url, json=spec) as resp:
        content_types = [
            "application/json-patch+json",
            "application/vnd.api+json",
            "application/json",
        ]
        try:
            if resp.headers["Content-Type"] in content_types:
                _json = await resp.json()
            else:
                print("response Content-Type not supported")
        except KeyError:
            _json = {}
        return await update_changed_flag(_json, resp.status, "post")


if __name__ == "__main__":
    import asyncio

    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
