#!/usr/bin/env python
# Info module template

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by
#   https://github.com/jgroom33/vmware_rest_code_generator
#
# Do not edit this file manually.
#
# Changes should be made in the swagger used to
#   generate this file or in the generator
#
#############################################

from __future__ import absolute_import, division, print_function

__metaclass__ = type
import socket
import json

DOCUMENTATION = """
module: nsi_api_v4_fres_by_freid
short_description: Handle resource of type nsi_api_v4_fres_by_freid
description: Handle resource of type nsi_api_v4_fres_by_freid
options:
  data:
    description:
    - 'Validate attributes are:'
    - ' - C(attributes) (dict): '
    - ' - C(id) (str): The unique identifier for the FRE resource'
    - ' - C(meta) (dict): A metadata object that contains non-standard meta information'
    - ' - C(relationships) (dict): '
    - ' - C(type) (str): The FRE resource type'
    - Used by I(state=['put'])
    type: dict
  fields:
    description:
    - (Optional) List of comma separated fields to be included in the response. Fields
      require full path (i.e. data.attributes.field)
    - Used by I(state=['get'])
    type: str
  freId:
    description:
    - Identifier of the FRE to be retrieved
    - Required with I(state=['get', 'patch', 'put'])
    - Used by I(state=['get', 'patch', 'put'])
    type: str
  include:
    description:
    - '(Optional) List of comma separated resources to be side-loaded. The allowed
      values are: fres, tpes, networkConstructs, equipment, expectations, frePlanned,
      freDiscovered, abstracts'
    - Used by I(state=['get'])
    type: str
  included:
    description:
    - Resources related to a FRE, such as FreData, EndPointData, TpeData, EquipmentData,
      EquipmentHolderData, FrePlannedData, FreExpectationData, FreDiscoveredData,
      ResiliencyControllerData, EncapsulatedResiliencyData
    - Used by I(state=['put'])
    type: list
  links:
    description:
    - Links related to the resource
    - 'Validate attributes are:'
    - ' - C(current) (str): The current page of data'
    - ' - C(first) (str): The first page of data'
    - ' - C(last) (str): The last page of data'
    - ' - C(next) (str): The next page of data'
    - ' - C(prev) (str): The previous page of data'
    - ' - C(self) (str): A `self` member, whose value is a URL for the relationship
      itself (a "relationship URL"). This URL allows the client to directly manipulate
      the relationship. For example, it would allow a client to remove an `author`
      from an `article` without deleting the people resource itself.'
    - Used by I(state=['put'])
    type: dict
  meta:
    description:
    - A metadata object that contains non-standard meta information
    - 'Validate attributes are:'
    - ' - C(absoluteTotal) (int): The unfiltered total number of entities in the data'
    - ' - C(aggregations) (list): The aggregated data based on a requested aggregation
      name and criteria'
    - ' - C(filtered) (bool): Flags whether the current object is filtered using `fields`
      query param or not'
    - ' - C(missingReferenceIds) (list): The list of missing resource IDs'
    - ' - C(missingReferences) (bool): boolean detailing if the GET FRE tree has any
      missing references'
    - ' - C(total) (int): The total number of entities in the data'
    - Used by I(state=['put'])
    type: dict
  operations:
    description:
    - Used by I(state=['patch'])
    type: list
  state:
    choices:
    - get
    - patch
    - put
    description: []
    type: str
author: []
version_added: 1.0.0
requirements:
- python >= 3.6
"""
IN_QUERY_PARAMETER = ["fields", "include"]
from ansible.module_utils.basic import env_fallback

try:
    from ansible_module.turbo.module import AnsibleTurboModule as AnsibleModule
except ImportError:
    from ansible.module_utils.basic import AnsibleModule
from ansible_collections.ciena.mcp.plugins.module_utils.mcp import (
    gen_args,
    open_session,
    update_changed_flag,
)


def prepare_argument_spec():
    argument_spec = {
        "mcp_hostname": dict(
            type="str", required=False, fallback=(env_fallback, ["MCP_HOST"])
        ),
        "mcp_username": dict(
            type="str", required=False, fallback=(env_fallback, ["MCP_USER"])
        ),
        "mcp_password": dict(
            type="str",
            required=False,
            no_log=True,
            fallback=(env_fallback, ["MCP_PASSWORD"]),
        ),
    }
    argument_spec["state"] = {"type": "str", "choices": ["get", "patch", "put"]}
    argument_spec["operations"] = {"type": "list", "operationIds": ["patch"]}
    argument_spec["meta"] = {"type": "dict", "operationIds": ["put"]}
    argument_spec["links"] = {"type": "dict", "operationIds": ["put"]}
    argument_spec["included"] = {"type": "list", "operationIds": ["put"]}
    argument_spec["include"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["freId"] = {"type": "str", "operationIds": ["get", "patch", "put"]}
    argument_spec["fields"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["data"] = {"type": "dict", "operationIds": ["put"]}
    return argument_spec


async def main():
    module_args = prepare_argument_spec()
    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)
    session = await open_session(
        mcp_hostname=module.params["mcp_hostname"],
        mcp_username=module.params["mcp_username"],
        mcp_password=module.params["mcp_password"],
    )
    result = await entry_point(module, session)
    module.exit_json(**result)


def url(params):
    return "https://{mcp_hostname}/nsi/api/v4/fres/{freId}".format(**params)


async def entry_point(module, session):
    func = globals()[("_" + module.params["state"])]
    return await func(module.params, session)


async def _get(params, session):
    _url = "https://{mcp_hostname}/nsi/api/v4/fres/{freId}".format(**params) + gen_args(
        params, IN_QUERY_PARAMETER
    )
    async with session.get(_url) as resp:
        content_types = [
            "application/json-patch+json",
            "application/vnd.api+json",
            "application/json",
        ]
        try:
            if resp.headers["Content-Type"] in content_types:
                _json = await resp.json()
            else:
                print("response Content-Type not supported")
        except KeyError:
            _json = {}
        return await update_changed_flag(_json, resp.status, "get")


async def _patch(params, session):
    accepted_fields = ["freId", "operations"]
    spec = {}
    for i in accepted_fields:
        if params[i] is not None:
            spec[i] = params[i]
    _url = "https://{mcp_hostname}/nsi/api/v4/fres/{freId}".format(**params) + gen_args(
        params, IN_QUERY_PARAMETER
    )
    async with session.patch(_url, json=spec) as resp:
        content_types = [
            "application/json-patch+json",
            "application/vnd.api+json",
            "application/json",
        ]
        try:
            if resp.headers["Content-Type"] in content_types:
                _json = await resp.json()
            else:
                print("response Content-Type not supported")
        except KeyError:
            _json = {}
        return await update_changed_flag(_json, resp.status, "patch")


async def _put(params, session):
    accepted_fields = ["data", "freId", "included", "links", "meta"]
    spec = {}
    for i in accepted_fields:
        if params[i] is not None:
            spec[i] = params[i]
    _url = "https://{mcp_hostname}/nsi/api/v4/fres/{freId}".format(**params) + gen_args(
        params, IN_QUERY_PARAMETER
    )
    async with session.put(_url, json=spec) as resp:
        content_types = [
            "application/json-patch+json",
            "application/vnd.api+json",
            "application/json",
        ]
        try:
            if resp.headers["Content-Type"] in content_types:
                _json = await resp.json()
            else:
                print("response Content-Type not supported")
        except KeyError:
            _json = {}
        return await update_changed_flag(_json, resp.status, "put")


if __name__ == "__main__":
    import asyncio

    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
