#!/usr/bin/env python
# Info module template

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by
#   https://github.com/jgroom33/vmware_rest_code_generator
#
# Do not edit this file manually.
#
# Changes should be made in the swagger used to
#   generate this file or in the generator
#
#############################################

from __future__ import absolute_import, division, print_function

__metaclass__ = type
import socket
import json

DOCUMENTATION = """
module: nsi_api_fres
short_description: Handle resource of type nsi_api_fres
description: Handle resource of type nsi_api_fres
options:
  childFreId:
    description:
    - The child FRE identifier to return its parents
    - Used by I(state=['get'])
    type: str
  data:
    description:
    - 'Validate attributes are:'
    - ' - C(attributes) (dict): '
    - ' - C(id) (str): The unique identifier for the FRE resource'
    - ' - C(meta) (dict): A metadata object that contains non-standard meta information'
    - ' - C(relationships) (dict): '
    - ' - C(type) (str): The FRE resource type'
    - Used by I(state=['post'])
    type: dict
  endpoint.tpe.concrete:
    description:
    - Concrete TPE identifier for endpoints
    - Used by I(state=['get'])
    type: str
  exclude:
    description:
    - '(Optional) A single given type to be excluded used in conjunction with the
      `childFreId` parameter. The allowed values are: actual, expectation'
    - Used by I(state=['get'])
    type: str
  fields:
    description:
    - (Optional) List of comma separated fields to be included in the response. Fields
      require full path (i.e. data.attributes.field)
    - Used by I(state=['get'])
    type: str
  freExpectations.equipmentIntent.id:
    description:
    - The equipment intent Id
    - Used by I(state=['get'])
    type: str
  freExpectations.intent.id:
    description:
    - The intent Id
    - Used by I(state=['get'])
    type: str
  freExpectations.serviceIntent.id:
    description:
    - The service intent Id
    - Used by I(state=['get'])
    type: str
  freType:
    description:
    - '(Optional) FRE types in comma separated list. The allowed values are: explicitRoute,
      explicitRouteGroup, snc, sncGroup'
    - Used by I(state=['get'])
    type: str
  identifierKey:
    description:
    - List of comma separated keys for an identifer object
    - Used by I(state=['get'])
    type: list
  identifierValue:
    description:
    - List of comma separated values for an identifier object
    - Used by I(state=['get'])
    type: list
  include:
    description:
    - '(Optional) List of comma separated resources to be side-loaded. The allowed
      values are: tpes, expectations, frePlanned, freDiscovered'
    - Used by I(state=['get'])
    type: str
  included:
    description:
    - Resources related to a FRE, such as FreData, EndPointData, TpeData, EquipmentData,
      EquipmentHolderData, FrePlannedData, FreExpectationData, FreDiscoveredData,
      ResiliencyControllerData, EncapsulatedResiliencyData
    - Used by I(state=['post'])
    type: list
  layerRate:
    description:
    - '(Optional) FRE layer rates in comma separated list. Only applied when Network
      Construct identifier is provided. The allowed values are: ETHERNET, OTU2, OTU4,
      OTSi, OMS, OS, PHY, OTS, ODU2, ODU4, DSR, DSR_10GE, DSR_100GE, DSR_ETHERNET'
    - Used by I(state=['get'])
    type: str
  limit:
    description:
    - (Optional) The size of a returned page. The default is 30
    - Used by I(state=['get'])
    type: str
  links:
    description:
    - Links related to the resource
    - 'Validate attributes are:'
    - ' - C(current) (str): The current page of data'
    - ' - C(first) (str): The first page of data'
    - ' - C(last) (str): The last page of data'
    - ' - C(next) (str): The next page of data'
    - ' - C(prev) (str): The previous page of data'
    - ' - C(self) (str): A `self` member, whose value is a URL for the relationship
      itself (a "relationship URL"). This URL allows the client to directly manipulate
      the relationship. For example, it would allow a client to remove an `author`
      from an `article` without deleting the people resource itself.'
    - Used by I(state=['post'])
    type: dict
  meta:
    description:
    - A metadata object that contains non-standard meta information
    - 'Validate attributes are:'
    - ' - C(absoluteTotal) (int): The unfiltered total number of entities in the data'
    - ' - C(aggregations) (list): The aggregated data based on a requested aggregation
      name and criteria'
    - ' - C(filtered) (bool): Flags whether the current object is filtered using `fields`
      query param or not'
    - ' - C(missingReferenceIds) (list): The list of missing resource IDs'
    - ' - C(missingReferences) (bool): boolean detailing if the GET FRE tree has any
      missing references'
    - ' - C(total) (int): The total number of entities in the data'
    - Used by I(state=['post'])
    type: dict
  networkConstruct.id:
    description:
    - Network Construct identifier
    - Used by I(state=['get'])
    type: str
  offset:
    description:
    - (Optional) Offset for the second page
    - Used by I(state=['get'])
    type: str
  roadmLineId:
    description:
    - (Optional) Find services configured over a roadmline based on the roadmline
      FRE identifier.
    - Used by I(state=['get'])
    type: str
  signalContentType:
    description:
    - (Optional) The identifier indicating type of parent to be returned. If specified,
      parent matching the criteria will be returned
    - Used by I(state=['get'])
    type: str
  state:
    choices:
    - get
    - post
    description: []
    type: str
  tpeId:
    description:
    - TPE identifier for endpoints
    - Used by I(state=['get'])
    type: str
author: []
version_added: 1.0.0
requirements:
- python >= 3.6
"""
IN_QUERY_PARAMETER = [
    "childFreId",
    "endpoint.tpe.concrete",
    "exclude",
    "fields",
    "freExpectations.equipmentIntent.id",
    "freExpectations.intent.id",
    "freExpectations.serviceIntent.id",
    "freType",
    "identifierKey",
    "identifierValue",
    "include",
    "layerRate",
    "limit",
    "networkConstruct.id",
    "offset",
    "roadmLineId",
    "signalContentType",
    "tpeId",
]
from ansible.module_utils.basic import env_fallback

try:
    from ansible_module.turbo.module import AnsibleTurboModule as AnsibleModule
except ImportError:
    from ansible.module_utils.basic import AnsibleModule
from ansible_collections.ciena.mcp.plugins.module_utils.mcp import (
    gen_args,
    open_session,
    update_changed_flag,
)


def prepare_argument_spec():
    argument_spec = {
        "mcp_hostname": dict(
            type="str", required=False, fallback=(env_fallback, ["MCP_HOST"])
        ),
        "mcp_username": dict(
            type="str", required=False, fallback=(env_fallback, ["MCP_USER"])
        ),
        "mcp_password": dict(
            type="str",
            required=False,
            no_log=True,
            fallback=(env_fallback, ["MCP_PASSWORD"]),
        ),
    }
    argument_spec["tpeId"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["state"] = {"type": "str", "choices": ["get", "post"]}
    argument_spec["signalContentType"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["roadmLineId"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["offset"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["networkConstruct_id"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["meta"] = {"type": "dict", "operationIds": ["post"]}
    argument_spec["links"] = {"type": "dict", "operationIds": ["post"]}
    argument_spec["limit"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["layerRate"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["included"] = {"type": "list", "operationIds": ["post"]}
    argument_spec["include"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["identifierValue"] = {"type": "list", "operationIds": ["get"]}
    argument_spec["identifierKey"] = {"type": "list", "operationIds": ["get"]}
    argument_spec["freType"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["freExpectations_serviceIntent_id"] = {
        "type": "str",
        "operationIds": ["get"],
    }
    argument_spec["freExpectations_intent_id"] = {
        "type": "str",
        "operationIds": ["get"],
    }
    argument_spec["freExpectations_equipmentIntent_id"] = {
        "type": "str",
        "operationIds": ["get"],
    }
    argument_spec["fields"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["exclude"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["endpoint_tpe_concrete"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["data"] = {"type": "dict", "operationIds": ["post"]}
    argument_spec["childFreId"] = {"type": "str", "operationIds": ["get"]}
    return argument_spec


async def main():
    module_args = prepare_argument_spec()
    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)
    session = await open_session(
        mcp_hostname=module.params["mcp_hostname"],
        mcp_username=module.params["mcp_username"],
        mcp_password=module.params["mcp_password"],
    )
    result = await entry_point(module, session)
    module.exit_json(**result)


def url(params):
    return "https://{mcp_hostname}/nsi/api/fres".format(**params)


async def entry_point(module, session):
    func = globals()[("_" + module.params["state"])]
    return await func(module.params, session)


async def _get(params, session):
    _url = "https://{mcp_hostname}/nsi/api/fres".format(**params) + gen_args(
        params, IN_QUERY_PARAMETER
    )
    async with session.get(_url) as resp:
        content_types = [
            "application/json-patch+json",
            "application/vnd.api+json",
            "application/json",
        ]
        try:
            if resp.headers["Content-Type"] in content_types:
                _json = await resp.json()
            else:
                print("response Content-Type not supported")
        except KeyError:
            _json = {}
        return await update_changed_flag(_json, resp.status, "get")


async def _post(params, session):
    accepted_fields = ["data", "included", "links", "meta"]
    spec = {}
    for i in accepted_fields:
        if params[i] is not None:
            spec[i] = params[i]
    _url = "https://{mcp_hostname}/nsi/api/fres".format(**params) + gen_args(
        params, IN_QUERY_PARAMETER
    )
    async with session.post(_url, json=spec) as resp:
        content_types = [
            "application/json-patch+json",
            "application/vnd.api+json",
            "application/json",
        ]
        try:
            if resp.headers["Content-Type"] in content_types:
                _json = await resp.json()
            else:
                print("response Content-Type not supported")
        except KeyError:
            _json = {}
        return await update_changed_flag(_json, resp.status, "post")


if __name__ == "__main__":
    import asyncio

    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
