#!/usr/bin/env python
# Info module template

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by
#   https://github.com/jgroom33/vmware_rest_code_generator
#
# Do not edit this file manually.
#
# Changes should be made in the swagger used to
#   generate this file or in the generator
#
#############################################

from __future__ import absolute_import, division, print_function

__metaclass__ = type
import socket
import json

DOCUMENTATION = """
module: nsi_api_v1_search_equipmentgroups
short_description: Handle resource of type nsi_api_v1_search_equipmentgroups
description: Handle resource of type nsi_api_v1_search_equipmentgroups
options:
  endDateMax:
    description:
    - '(Optional) Maximum value of endDate, format is: yyyy-MM-dd''T''HH:mm:ss.SSSZ'
    - Used by I(state=['get'])
    type: str
  endDateMin:
    description:
    - '(Optional) Minimum value of endDate, format is: yyyy-MM-dd''T''HH:mm:ss.SSSZ'
    - Used by I(state=['get'])
    type: str
  equipment.id:
    description:
    - (Optional) Comma separated list of equipment identifiers
    - Used by I(state=['get'])
    type: str
  equipmentGroupExpectations.equipmentIntent.id:
    description:
    - (Optional) Equipment Intent Identifier
    - Used by I(state=['get'])
    type: str
  fields:
    description:
    - (Optional) List of comma separated fields to be included in the response. Fields
      require full path (i.e. data.attributes.field)
    - Used by I(state=['get'])
    type: str
  id:
    description:
    - (Optional) Comma separated list of Equipment group identifiers to retrieve
    - Used by I(state=['get'])
    type: str
  include:
    description:
    - '(Optional) List of comma separated resources to be side-loaded. The allowed
      values are: expectations, networkConstructs, discovered, planned'
    - Used by I(state=['get'])
    type: str
  limit:
    description:
    - The size of a returned page
    - Used by I(state=['get'])
    type: str
  metaDataFields:
    description:
    - '(Optional) List of meta data to be included. The allowed values are: type,
      subType'
    - Used by I(state=['get'])
    type: str
  metaDataQualifiers:
    description:
    - '(Optional) List of meta data options. The allowed values are: absoluteTotals'
    - Used by I(state=['get'])
    type: str
  name:
    description:
    - (Optional) Equipment group name
    - Used by I(state=['get'])
    type: str
  networkConstruct.id:
    description:
    - (Optional) Network Construct identifier
    - Used by I(state=['get'])
    type: str
  offset:
    description:
    - (Optional) Offset for current index of data to return
    - Used by I(state=['get'])
    type: str
  resourceState:
    description:
    - '(Optional) List of resource states. By default, if no value for this parameter
      is specified, root and unknown states are filtered out. The allowed values are:
      root, planned, discovered, plannedAndDiscovered, unknown'
    - Used by I(state=['get'])
    type: str
  searchFields:
    description:
    - (Optional) List of comma separated fields to search on. If none are specified,
      all supported fields are implied. Fields require full path (e.g. data.attributes.name)
    - Used by I(state=['get'])
    type: str
  searchText:
    description:
    - (Optional) The searchable text
    - Used by I(state=['get'])
    type: str
  sortBy:
    description:
    - (Optional) List of comma separated fields by which to sort the result. Fields
      require full path (i.e. data.attributes.field). A dash or negative sign before
      a field indicates descending order; by default ascending order is used
    - Used by I(state=['get'])
    type: str
  startDateMax:
    description:
    - '(Optional) Maximum value of startDate, format is: yyyy-MM-dd''T''HH:mm:ss.SSSZ'
    - Used by I(state=['get'])
    type: str
  startDateMin:
    description:
    - '(Optional) Minimum value of startDate, format is: yyyy-MM-dd''T''HH:mm:ss.SSSZ'
    - Used by I(state=['get'])
    type: str
  state:
    choices:
    - get
    description: []
    type: str
  subType:
    description:
    - (Optional) List of Equipment group sub type
    - Used by I(state=['get'])
    type: str
  type:
    description:
    - (Optional) List of Equipment group type
    - Used by I(state=['get'])
    type: str
author: []
version_added: 1.0.0
requirements:
- python >= 3.6
"""
IN_QUERY_PARAMETER = [
    "endDateMax",
    "endDateMin",
    "equipment.id",
    "equipmentGroupExpectations.equipmentIntent.id",
    "fields",
    "id",
    "include",
    "limit",
    "metaDataFields",
    "metaDataQualifiers",
    "name",
    "networkConstruct.id",
    "offset",
    "resourceState",
    "searchFields",
    "searchText",
    "sortBy",
    "startDateMax",
    "startDateMin",
    "subType",
    "type",
]
from ansible.module_utils.basic import env_fallback

try:
    from ansible_module.turbo.module import AnsibleTurboModule as AnsibleModule
except ImportError:
    from ansible.module_utils.basic import AnsibleModule
from ansible_collections.ciena.mcp.plugins.module_utils.mcp import (
    gen_args,
    open_session,
    update_changed_flag,
)


def prepare_argument_spec():
    argument_spec = {
        "mcp_hostname": dict(
            type="str", required=False, fallback=(env_fallback, ["MCP_HOST"])
        ),
        "mcp_username": dict(
            type="str", required=False, fallback=(env_fallback, ["MCP_USER"])
        ),
        "mcp_password": dict(
            type="str",
            required=False,
            no_log=True,
            fallback=(env_fallback, ["MCP_PASSWORD"]),
        ),
    }
    argument_spec["type"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["subType"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["state"] = {"type": "str", "choices": ["get"]}
    argument_spec["startDateMin"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["startDateMax"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["sortBy"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["searchText"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["searchFields"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["resourceState"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["offset"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["networkConstruct_id"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["name"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["metaDataQualifiers"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["metaDataFields"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["limit"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["include"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["id"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["fields"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["equipmentGroupExpectations_equipmentIntent_id"] = {
        "type": "str",
        "operationIds": ["get"],
    }
    argument_spec["equipment_id"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["endDateMin"] = {"type": "str", "operationIds": ["get"]}
    argument_spec["endDateMax"] = {"type": "str", "operationIds": ["get"]}
    return argument_spec


async def main():
    module_args = prepare_argument_spec()
    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)
    session = await open_session(
        mcp_hostname=module.params["mcp_hostname"],
        mcp_username=module.params["mcp_username"],
        mcp_password=module.params["mcp_password"],
    )
    result = await entry_point(module, session)
    module.exit_json(**result)


def url(params):
    return "https://{mcp_hostname}/nsi/api/v1/search/equipmentGroups".format(**params)


async def entry_point(module, session):
    func = globals()[("_" + module.params["state"])]
    return await func(module.params, session)


async def _get(params, session):
    _url = "https://{mcp_hostname}/nsi/api/v1/search/equipmentGroups".format(
        **params
    ) + gen_args(params, IN_QUERY_PARAMETER)
    async with session.get(_url) as resp:
        content_types = [
            "application/json-patch+json",
            "application/vnd.api+json",
            "application/json",
        ]
        try:
            if resp.headers["Content-Type"] in content_types:
                _json = await resp.json()
            else:
                print("response Content-Type not supported")
        except KeyError:
            _json = {}
        return await update_changed_flag(_json, resp.status, "get")


if __name__ == "__main__":
    import asyncio

    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
