#!/usr/bin/env python
# Info module template

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by
#   https://github.com/jgroom33/vmware_rest_code_generator
#
# Do not edit this file manually.
#
# Changes should be made in the swagger used to
#   generate this file or in the generator
#
#############################################

from __future__ import absolute_import, division, print_function

__metaclass__ = type
import socket
import json

DOCUMENTATION = """
module: nsi_api_v3_physicallocations_by_id_expectations
short_description: Handle resource of type nsi_api_v3_physicallocations_by_id_expectations
description: Handle resource of type nsi_api_v3_physicallocations_by_id_expectations
options:
  attributes:
    description:
    - 'Validate attributes are:'
    - ' - C(additionalAttributes) (dict): Various miscellaneous attributes that do
      not necessarily belong in the parent resource. Attributes are populated dynamically
      and therefore cannot be documented here.'
    - ' - C(geoLocation) (dict): The geography location of the device'
    - ' - C(intentId) (str): The intent id of the physical expectation location'
    - ' - C(name) (str): Name of the physical location.'
    - Used by I(state=['post'])
    type: dict
  id:
    description:
    - Identifier of the physical location under which to create the expectation
    - Required with I(state=['post'])
    - Used by I(state=['post'])
    type: str
  state:
    choices:
    - post
    description: []
    type: str
  type:
    description:
    - The physical location expectation type
    - Used by I(state=['post'])
    type: str
author: []
version_added: 1.0.0
requirements:
- python >= 3.6
"""
IN_QUERY_PARAMETER = []
from ansible.module_utils.basic import env_fallback

try:
    from ansible_module.turbo.module import AnsibleTurboModule as AnsibleModule
except ImportError:
    from ansible.module_utils.basic import AnsibleModule
from ansible_collections.ciena.mcp.plugins.module_utils.mcp import (
    gen_args,
    open_session,
    update_changed_flag,
)


def prepare_argument_spec():
    argument_spec = {
        "mcp_hostname": dict(
            type="str", required=False, fallback=(env_fallback, ["MCP_HOST"])
        ),
        "mcp_username": dict(
            type="str", required=False, fallback=(env_fallback, ["MCP_USER"])
        ),
        "mcp_password": dict(
            type="str",
            required=False,
            no_log=True,
            fallback=(env_fallback, ["MCP_PASSWORD"]),
        ),
    }
    argument_spec["type"] = {"type": "str", "operationIds": ["post"]}
    argument_spec["state"] = {"type": "str", "choices": ["post"]}
    argument_spec["id"] = {"type": "str", "operationIds": ["post", "post"]}
    argument_spec["attributes"] = {"type": "dict", "operationIds": ["post"]}
    return argument_spec


async def main():
    module_args = prepare_argument_spec()
    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)
    session = await open_session(
        mcp_hostname=module.params["mcp_hostname"],
        mcp_username=module.params["mcp_username"],
        mcp_password=module.params["mcp_password"],
    )
    result = await entry_point(module, session)
    module.exit_json(**result)


def url(params):
    return (
        "https://{mcp_hostname}/nsi/api/v3/physicalLocations/{id}/expectations".format(
            **params
        )
    )


async def entry_point(module, session):
    func = globals()[("_" + module.params["state"])]
    return await func(module.params, session)


async def _post(params, session):
    accepted_fields = ["attributes", "id", "type"]
    spec = {}
    for i in accepted_fields:
        if params[i] is not None:
            spec[i] = params[i]
    _url = (
        "https://{mcp_hostname}/nsi/api/v3/physicalLocations/{id}/expectations".format(
            **params
        )
        + gen_args(params, IN_QUERY_PARAMETER)
    )
    async with session.post(_url, json=spec) as resp:
        content_types = [
            "application/json-patch+json",
            "application/vnd.api+json",
            "application/json",
        ]
        try:
            if resp.headers["Content-Type"] in content_types:
                _json = await resp.json()
            else:
                print("response Content-Type not supported")
        except KeyError:
            _json = {}
        return await update_changed_flag(_json, resp.status, "post")


if __name__ == "__main__":
    import asyncio

    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
