---
name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: build
        run: |
          ansible-galaxy collection build
      - name: release
        run: |
          ls *.tar.gz | xargs ansible-galaxy collection publish --api-key ${{ secrets.GALAXY_API_KEY }}
